development:
  adapter: postgresql
  host: localhost
  database: tscope_dev
  username: postgres
  password: LkPLYN1i

test:
  adapter: postgresql
  host: localhost
  database: tscope_test
  username: postgres
  password: LkPLYN1i